name: publish node package

on:
  push:
    branches:
      - main

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整提交历史
          clean: true # 清理工作目录
      - uses: pnpm/action-setup@v4
        with:
          version: 8
          cache: pnpm
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
          registry-url: https://registry.npmjs.org/
      # 配置 git 用户
      - name: Setup git user
        run: |
          git config --global user.email ${{secrets.USER_EMAIL}}
          git config --global user.name ${{secrets.USER_NAME}}
      - run: pnpm install
      - run: pnpm build
      - name: Sync git tags
        run: |
          git fetch --prune --prune-tags  # 清理已删除的远程标签
          git fetch --tags -f
      - run: export RELEASE_IT_TOKEN=${{secrets.RELEASE_IT_TOKEN}} && pnpm release --ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
